all_empresas:
    path:     /empresas/all
    defaults: { _controller: GfctBundle:Empresas:all }

empresa_crear:
    path:     /empresas/new
    defaults: { _controller: GfctBundle:Empresas:nuevo }

empresa_exito:
    path:     /empresas/exito
    defaults: { _controller: GfctBundle:Empresas:exito }

nuevo_empresas_alumnos:
    path:     /alumnos/all
    defaults: { _controller: GfctBundle:Alumnos:all }

api_mostrar_empresas:
    path:     /apiget/empresas
    defaults: { _controller: GfctBundle:Api:empresas }
    methods: [GET]

api_insertar:
    path:     /apipost
    defaults: { _controller: GfctBundle:Api:empresasinsert }

all_profesores:
    path:     /profesores/all
    defaults: { _controller: GfctBundle:Profesores:all }

profesores_crear:
    path:     /profesores/new
    defaults: { _controller: GfctBundle:Profesores:nuevo }

profesor_exito:
    path:     /profesores/exito
    defaults: { _controller: GfctBundle:Profesores:exito }

api_mostrar_profesores:
    path:     /apiget/profesores
    defaults: { _controller: GfctBundle:Api:profesores }
    methods: [GET]

registro:
    path:     /register
    defaults: { _controller: GfctBundle:Default:register }

admin:
    path:     /admin
    defaults: { _controller: GfctBundle:Admin:all }

usuarios_login:
    path:     /usuarios/login
    defaults: { _controller: GfctBundle:Default:login }

usuario_login:
    path:     /usuarios/login
    defaults: { _controller: GfctBundle:Default:login }

usuarios_logout:
    path:     /usuarios/logout
